// Generated by generate_candidates.R — do not hand-edit.
const CANDIDATES = 
{
  "hda": {
    "sequential": [
      {
        "id": "hda-seq-blue-cream-standard",
        "brand": "hda",
        "type": "sequential",
        "anchorLabel": "Blue -> cream",
        "inspiration": {
          "dark": "Blue",
          "light": "shared cream (H~80, C~10)"
        },
        "nudgeNote": "Off Blue: hue +0° (source 259° -> final 259°), chroma 67 -> 60 (dark end), luminance 41 -> 26 (dark end); light end anchors to a shared cream tone (H~80, C~10) at L~95, not this color's own hue.",
        "variant": "standard",
        "variantLabel": "Standard (linear HCL sweep)",
        "params": {
          "h1": 259.2288,
          "c1": 60,
          "l1": 26,
          "l2": 95,
          "power": 1,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -6.851,
        "hexSmooth": ["#153985", "#004285", "#004B85", "#005386", "#005A86", "#006187", "#006887", "#006E88", "#007588", "#007B89", "#008189", "#00878A", "#0F8C8A", "#2A928B", "#3C978C", "#4B9D8E", "#59A290", "#66A792", "#73AC94", "#7FB198", "#8AB79B", "#95BCA0", "#A0C1A4", "#ABC6AA", "#B5CBB0", "#BFD0B6", "#C9D5BD", "#D2DBC4", "#DBE0CC", "#E3E6D4", "#EBEBDC", "#F3F1E4"],
        "hexBinned": ["#153985", "#006287", "#008389", "#529F8F", "#92BA9E", "#C7D4BC", "#F3F1E4"],
        "warnings": []
      },
      {
        "id": "hda-seq-blue-cream-wide_contrast",
        "brand": "hda",
        "type": "sequential",
        "anchorLabel": "Blue -> cream",
        "inspiration": {
          "dark": "Blue",
          "light": "shared cream (H~80, C~10)"
        },
        "nudgeNote": "Off Blue: hue +0° (source 259° -> final 259°), chroma 67 -> 60 (dark end), luminance 41 -> 26 (dark end); light end anchors to a shared cream tone (H~80, C~10) at L~95, not this color's own hue.",
        "variant": "wide_contrast",
        "variantLabel": "Wide-contrast (deeper dark end, punchier chroma, eased curve)",
        "params": {
          "h1": 259.2288,
          "c1": 72,
          "l1": 20,
          "l2": 96,
          "power": 1.2,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -6.851,
        "hexSmooth": ["#002696", "#00368E", "#00428A", "#004C89", "#005588", "#005D88", "#006589", "#006D89", "#00748A", "#007C8B", "#00838C", "#008A8D", "#00908E", "#1D9790", "#389D91", "#4CA394", "#5CA996", "#6CAF99", "#7AB59D", "#87BBA0", "#94C0A5", "#A0C6AA", "#ABCBAF", "#B6D0B5", "#C1D5BB", "#CADAC2", "#D3DFC8", "#DCE4CF", "#E4E9D6", "#EBEDDC", "#F1F1E3", "#F6F4E7"],
        "hexBinned": ["#002696", "#005E88", "#00858C", "#54A695", "#9CC4A8", "#D2DEC7", "#F6F4E7"],
        "warnings": []
      },
      {
        "id": "hda-seq-coral-cream-standard",
        "brand": "hda",
        "type": "sequential",
        "anchorLabel": "Coral -> cream",
        "inspiration": {
          "dark": "Coral",
          "light": "shared cream (H~80, C~10)"
        },
        "nudgeNote": "Off Coral: hue +0° (source 20° -> final 20°), chroma 99 -> 85 (dark end), luminance 61 -> 30 (dark end); light end anchors to a shared cream tone (H~80, C~10) at L~95, not this color's own hue.",
        "variant": "standard",
        "variantLabel": "Standard (linear HCL sweep)",
        "params": {
          "h1": 20.415,
          "c1": 85,
          "l1": 30,
          "l2": 95,
          "power": 1,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -14.2222,
        "hexSmooth": ["#872300", "#8A2C00", "#8E3400", "#913B00", "#944300", "#984A05", "#9B5113", "#9E581D", "#A15F25", "#A4652E", "#A86C36", "#AB723D", "#AE7945", "#B1804D", "#B48655", "#B78D5D", "#BA9365", "#BD996D", "#C0A075", "#C3A67D", "#C7AD85", "#CAB38D", "#CDB996", "#D1C09E", "#D5C6A7", "#D8CCB0", "#DCD2B8", "#E1D9C1", "#E5DFCA", "#E9E5D3", "#EEEBDC", "#F3F1E4"],
        "hexBinned": ["#872300", "#984B08", "#A96E38", "#B89061", "#C9B18B", "#DCD1B7", "#F3F1E4"],
        "warnings": []
      },
      {
        "id": "hda-seq-coral-cream-wide_contrast",
        "brand": "hda",
        "type": "sequential",
        "anchorLabel": "Coral -> cream",
        "inspiration": {
          "dark": "Coral",
          "light": "shared cream (H~80, C~10)"
        },
        "nudgeNote": "Off Coral: hue +0° (source 20° -> final 20°), chroma 99 -> 85 (dark end), luminance 61 -> 30 (dark end); light end anchors to a shared cream tone (H~80, C~10) at L~95, not this color's own hue.",
        "variant": "wide_contrast",
        "variantLabel": "Wide-contrast (deeper dark end, punchier chroma, eased curve)",
        "params": {
          "h1": 20.415,
          "c1": 97,
          "l1": 24,
          "l2": 96,
          "power": 1.2,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -14.2222,
        "hexSmooth": ["#7B0100", "#801600", "#852300", "#8A2E00", "#8F3800", "#944100", "#984A00", "#9D5200", "#A15B12", "#A56322", "#A96B2E", "#AD733A", "#B17B44", "#B5824E", "#B98A58", "#BD9262", "#C0996B", "#C4A075", "#C8A87E", "#CBAF87", "#CFB690", "#D3BD99", "#D6C3A2", "#DACAAB", "#DED0B4", "#E1D6BC", "#E5DCC5", "#E9E2CD", "#ECE7D5", "#F0ECDC", "#F3F1E2", "#F6F4E7"],
        "hexBinned": ["#7B0100", "#944200", "#AB6E32", "#BF9566", "#D1BA96", "#E4DBC3", "#F6F4E7"],
        "warnings": []
      },
      {
        "id": "hda-seq-sea-green-cream-standard",
        "brand": "hda",
        "type": "sequential",
        "anchorLabel": "Sea Green -> cream",
        "inspiration": {
          "dark": "Sea Green",
          "light": "shared cream (H~80, C~10)"
        },
        "nudgeNote": "Off Sea Green: hue +2° (source 130° -> final 132°), chroma 39 -> 55 (dark end), luminance 72 -> 28 (dark end); light end anchors to a shared cream tone (H~80, C~10) at L~95, not this color's own hue.",
        "variant": "standard",
        "variantLabel": "Standard (linear HCL sweep)",
        "params": {
          "h1": 132.194,
          "c1": 55,
          "l1": 28,
          "l2": 95,
          "power": 1,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 2,
        "sourceChromaDelta": 16.2817,
        "hexSmooth": ["#005100", "#005600", "#005A00", "#0F5F09", "#216316", "#2E681F", "#396D27", "#42712F", "#4C7637", "#547B3E", "#5D8045", "#65854D", "#6D8954", "#758E5B", "#7D9362", "#84996A", "#8C9E71", "#93A378", "#9BA880", "#A2AD87", "#A9B38F", "#B0B896", "#B7BD9E", "#BEC3A6", "#C5C9AD", "#CCCEB5", "#D2D4BD", "#D9DAC5", "#E0DFCD", "#E6E5D5", "#EDEBDC", "#F3F1E4"],
        "hexBinned": ["#005100", "#306921", "#608148", "#889B6D", "#AEB694", "#D1D3BC", "#F3F1E4"],
        "warnings": []
      },
      {
        "id": "hda-seq-sea-green-cream-wide_contrast",
        "brand": "hda",
        "type": "sequential",
        "anchorLabel": "Sea Green -> cream",
        "inspiration": {
          "dark": "Sea Green",
          "light": "shared cream (H~80, C~10)"
        },
        "nudgeNote": "Off Sea Green: hue +2° (source 130° -> final 132°), chroma 39 -> 55 (dark end), luminance 72 -> 28 (dark end); light end anchors to a shared cream tone (H~80, C~10) at L~95, not this color's own hue.",
        "variant": "wide_contrast",
        "variantLabel": "Wide-contrast (deeper dark end, punchier chroma, eased curve)",
        "params": {
          "h1": 132.194,
          "c1": 67,
          "l1": 22,
          "l2": 96,
          "power": 1.2,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 2,
        "sourceChromaDelta": 16.2817,
        "hexSmooth": ["#004600", "#004B00", "#005100", "#005700", "#005D00", "#176300", "#296905", "#376F1A", "#447527", "#4F7B33", "#59813D", "#648747", "#6D8D50", "#77935A", "#809963", "#899F6C", "#92A575", "#9AAA7E", "#A2B086", "#AAB68F", "#B2BC97", "#BAC2A0", "#C1C8A8", "#C8CDB0", "#CFD3B8", "#D6D8C0", "#DCDEC8", "#E2E3CF", "#E8E8D6", "#EDECDD", "#F2F1E3", "#F6F4E7"],
        "hexBinned": ["#004600", "#1B6400", "#5D8340", "#8DA270", "#B7C09D", "#DBDDC7", "#F6F4E7"],
        "warnings": []
      }
    ],
    "diverging": [
      {
        "id": "hda-div-blue-vs-coral-standard",
        "brand": "hda",
        "type": "diverging",
        "anchorLabel": "Blue vs Coral",
        "inspiration": {
          "arm1": "Blue",
          "arm2": "Coral"
        },
        "nudgeNote": "Off Blue (arm 1, hue 259°) and Coral (arm 2, hue 20°): shared chroma target 70 (arm1 source C=67, arm2 source C=99), luminance sweep 28 -> 95 into a shared cream center (H~80, C~10), not a fully neutral one.",
        "variant": "standard",
        "variantLabel": "Standard (linear HCL sweep)",
        "params": {
          "h1": 259.2288,
          "h2": 20.415,
          "c1": 70,
          "l1": 28,
          "l2": 95,
          "power": 1,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -13.0366,
        "hexSmooth": ["#083C95", "#005193", "#006192", "#006F91", "#007C90", "#008890", "#00948F", "#329E90", "#58A992", "#75B397", "#8FBD9E", "#A7C7A7", "#BDD1B4", "#D1DBC2", "#E3E6D3", "#F3F1E4", "#F3F1E4", "#E8E4D3", "#DED7C2", "#D5CAB0", "#CDBDA0", "#C4B08F", "#BDA27F", "#B59570", "#AE8861", "#A67A52", "#9F6D44", "#985F36", "#915228", "#894419", "#823508", "#7A2500"],
        "hexBinned": ["#083C95", "#008890", "#8FBD9E", "#F3F1E4", "#C4B08F", "#9F6D44", "#7A2500"],
        "warnings": []
      },
      {
        "id": "hda-div-blue-vs-coral-wide_contrast",
        "brand": "hda",
        "type": "diverging",
        "anchorLabel": "Blue vs Coral",
        "inspiration": {
          "arm1": "Blue",
          "arm2": "Coral"
        },
        "nudgeNote": "Off Blue (arm 1, hue 259°) and Coral (arm 2, hue 20°): shared chroma target 70 (arm1 source C=67, arm2 source C=99), luminance sweep 28 -> 95 into a shared cream center (H~80, C~10), not a fully neutral one.",
        "variant": "wide_contrast",
        "variantLabel": "Wide-contrast (deeper dark end, punchier chroma, eased curve)",
        "params": {
          "h1": 259.2288,
          "h2": 20.415,
          "c1": 82,
          "l1": 22,
          "l2": 96,
          "power": 1.2,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -13.0366,
        "hexSmooth": ["#0029A7", "#004898", "#005B94", "#006C92", "#007C92", "#008A92", "#009893", "#32A495", "#5EB099", "#7EBC9F", "#9AC6A8", "#B3D1B3", "#C8DBC0", "#DBE4CE", "#EBEDDC", "#F6F4E7", "#F6F4E7", "#EFEBDC", "#E7E1CD", "#DFD4BD", "#D6C7AC", "#CEB99A", "#C5AB88", "#BD9C76", "#B48C64", "#AB7D51", "#A26C3E", "#995C29", "#8F4B0F", "#853900", "#7B2500", "#700800"],
        "hexBinned": ["#0029A7", "#008A92", "#9AC6A8", "#F6F4E7", "#CEB99A", "#A26C3E", "#700800"],
        "warnings": []
      },
      {
        "id": "hda-div-blue-vs-yellow-standard",
        "brand": "hda",
        "type": "diverging",
        "anchorLabel": "Blue vs Yellow",
        "inspiration": {
          "arm1": "Blue",
          "arm2": "Yellow"
        },
        "nudgeNote": "Off Blue (arm 1, hue 259°) and Yellow (arm 2, hue 53°): shared chroma target 65 (arm1 source C=67, arm2 source C=83), luminance sweep 28 -> 95 into a shared cream center (H~80, C~10), not a fully neutral one.",
        "variant": "standard",
        "variantLabel": "Standard (linear HCL sweep)",
        "params": {
          "h1": 259.2288,
          "h2": 52.6755,
          "c1": 65,
          "l1": 28,
          "l2": 95,
          "power": 1,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -9.9364,
        "hexSmooth": ["#173D8E", "#00508E", "#00608E", "#006E8E", "#007B8E", "#00878E", "#03938E", "#3D9E90", "#5DA893", "#79B297", "#91BC9F", "#A8C6A9", "#BED0B5", "#D1DBC3", "#E3E6D3", "#F3F1E4", "#F3F1E4", "#E8E4D3", "#DDD8C2", "#D2CBB1", "#C8BEA0", "#BEB28F", "#B4A57E", "#AB996D", "#A18D5B", "#988049", "#907435", "#87681B", "#7E5C00", "#765100", "#6D4500", "#643A00"],
        "hexBinned": ["#173D8E", "#00878E", "#91BC9F", "#F3F1E4", "#BEB28F", "#907435", "#643A00"],
        "warnings": []
      },
      {
        "id": "hda-div-blue-vs-yellow-wide_contrast",
        "brand": "hda",
        "type": "diverging",
        "anchorLabel": "Blue vs Yellow",
        "inspiration": {
          "arm1": "Blue",
          "arm2": "Yellow"
        },
        "nudgeNote": "Off Blue (arm 1, hue 259°) and Yellow (arm 2, hue 53°): shared chroma target 65 (arm1 source C=67, arm2 source C=83), luminance sweep 28 -> 95 into a shared cream center (H~80, C~10), not a fully neutral one.",
        "variant": "wide_contrast",
        "variantLabel": "Wide-contrast (deeper dark end, punchier chroma, eased curve)",
        "params": {
          "h1": 259.2288,
          "h2": 52.6755,
          "c1": 77,
          "l1": 22,
          "l2": 96,
          "power": 1.2,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -9.9364,
        "hexSmooth": ["#002B9D", "#004792", "#005A90", "#006B8F", "#007B90", "#008991", "#009792", "#3CA395", "#62AF99", "#81BBA0", "#9CC6A9", "#B4D0B4", "#C9DAC0", "#DBE4CE", "#EBEDDC", "#F6F4E7", "#F6F4E7", "#EFECDC", "#E6E1CD", "#DCD5BD", "#D2C9AC", "#C7BB99", "#BDAE86", "#B2A072", "#A7925D", "#9D8346", "#92742A", "#876600", "#7C5700", "#704800", "#653900", "#592B00"],
        "hexBinned": ["#002B9D", "#008991", "#9CC6A9", "#F6F4E7", "#C7BB99", "#92742A", "#592B00"],
        "warnings": []
      },
      {
        "id": "hda-div-lavender-vs-sea-green-standard",
        "brand": "hda",
        "type": "diverging",
        "anchorLabel": "Lavender vs Sea Green",
        "inspiration": {
          "arm1": "Lavender",
          "arm2": "Sea Green"
        },
        "nudgeNote": "Off Lavender (arm 1, hue 336°) and Sea Green (arm 2, hue 130°): shared chroma target 45 (arm1 source C=29, arm2 source C=39), luminance sweep 28 -> 95 into a shared cream center (H~80, C~10), not a fully neutral one.",
        "variant": "standard",
        "variantLabel": "Standard (linear HCL sweep)",
        "params": {
          "h1": 336.36,
          "h2": 130.194,
          "c1": 45,
          "l1": 28,
          "l2": 95,
          "power": 1,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": 10.9138,
        "hexSmooth": ["#722453", "#763469", "#75457B", "#715789", "#6B6894", "#65789C", "#6388A1", "#6696A5", "#70A3A7", "#7FAFAA", "#92BBAE", "#A6C6B4", "#BBD1BD", "#CFDBC8", "#E2E6D5", "#F3F1E4", "#F3F1E4", "#E6E5D5", "#D8D9C5", "#CBCDB6", "#BDC1A7", "#AFB698", "#A0AA89", "#929F7B", "#83956D", "#748A5F", "#658051", "#557543", "#446B35", "#326227", "#1B5817", "#004F01"],
        "hexBinned": ["#722453", "#65789C", "#92BBAE", "#F3F1E4", "#AFB698", "#658051", "#004F01"],
        "warnings": []
      },
      {
        "id": "hda-div-lavender-vs-sea-green-wide_contrast",
        "brand": "hda",
        "type": "diverging",
        "anchorLabel": "Lavender vs Sea Green",
        "inspiration": {
          "arm1": "Lavender",
          "arm2": "Sea Green"
        },
        "nudgeNote": "Off Lavender (arm 1, hue 336°) and Sea Green (arm 2, hue 130°): shared chroma target 45 (arm1 source C=29, arm2 source C=39), luminance sweep 28 -> 95 into a shared cream center (H~80, C~10), not a fully neutral one.",
        "variant": "wide_contrast",
        "variantLabel": "Wide-contrast (deeper dark end, punchier chroma, eased curve)",
        "params": {
          "h1": 336.36,
          "h2": 130.194,
          "c1": 57,
          "l1": 22,
          "l2": 96,
          "power": 1.2,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": 10.9138,
        "hexSmooth": ["#70004B", "#751866", "#75367C", "#704F8D", "#686599", "#6279A2", "#608BA8", "#659CAC", "#72ABAF", "#85B8B3", "#9AC5B8", "#B0D0BE", "#C5DBC7", "#D8E4D2", "#E9EDDD", "#F6F4E7", "#F6F4E7", "#EDECDD", "#E2E2CF", "#D5D7C0", "#C7CBB1", "#B8BFA0", "#A8B390", "#98A77F", "#879A6D", "#758E5B", "#628149", "#4E7536", "#386820", "#1B5C00", "#005000", "#004400"],
        "hexBinned": ["#70004B", "#6279A2", "#9AC5B8", "#F6F4E7", "#B8BFA0", "#628149", "#004400"],
        "warnings": []
      }
    ]
  },
  "hfv": {
    "sequential": [
      {
        "id": "hfv-seq-shadow-cream-standard",
        "brand": "hfv",
        "type": "sequential",
        "anchorLabel": "Shadow -> cream",
        "inspiration": {
          "dark": "Shadow",
          "light": "shared cream (H~80, C~10)"
        },
        "nudgeNote": "Off Shadow: hue +0° (source 247° -> final 247°), chroma 27 -> 45 (dark end), luminance 31 -> 24 (dark end); light end anchors to a shared cream tone (H~80, C~10) at L~95, not this color's own hue.",
        "variant": "standard",
        "variantLabel": "Standard (linear HCL sweep)",
        "params": {
          "h1": 246.5788,
          "c1": 45,
          "l1": 24,
          "l2": 95,
          "power": 1,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": 18.1696,
        "hexSmooth": ["#003C6C", "#00436D", "#004A6E", "#005170", "#005771", "#005D73", "#006375", "#006976", "#006F78", "#0D757A", "#217B7C", "#2F817E", "#3C8680", "#488C82", "#539285", "#5E9788", "#689D8B", "#73A28E", "#7DA892", "#87AD96", "#91B39B", "#9BB8A0", "#A5BDA5", "#AEC3AB", "#B8C8B1", "#C1CEB8", "#CAD4BF", "#D2D9C6", "#DBDFCD", "#E3E5D5", "#EBEBDC", "#F3F1E4"],
        "hexBinned": ["#003C6C", "#005E73", "#267D7C", "#639A89", "#98B69E", "#C8D3BD", "#F3F1E4"],
        "warnings": []
      },
      {
        "id": "hfv-seq-shadow-cream-wide_contrast",
        "brand": "hfv",
        "type": "sequential",
        "anchorLabel": "Shadow -> cream",
        "inspiration": {
          "dark": "Shadow",
          "light": "shared cream (H~80, C~10)"
        },
        "nudgeNote": "Off Shadow: hue +0° (source 247° -> final 247°), chroma 27 -> 45 (dark end), luminance 31 -> 24 (dark end); light end anchors to a shared cream tone (H~80, C~10) at L~95, not this color's own hue.",
        "variant": "wide_contrast",
        "variantLabel": "Wide-contrast (deeper dark end, punchier chroma, eased curve)",
        "params": {
          "h1": 246.5788,
          "c1": 57,
          "l1": 18,
          "l2": 96,
          "power": 1.2,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": 18.1696,
        "hexSmooth": ["#003276", "#003B72", "#004371", "#004B71", "#005272", "#005A74", "#006175", "#006877", "#007079", "#00777C", "#007E7E", "#158481", "#2E8B83", "#409286", "#50988A", "#5E9F8D", "#6BA591", "#77AB95", "#83B19A", "#8FB79F", "#9ABDA4", "#A5C3AA", "#AFC8B0", "#B9CEB6", "#C3D3BC", "#CCD9C3", "#D4DEC9", "#DCE3D0", "#E4E8D7", "#EBEDDD", "#F1F1E3", "#F6F4E7"],
        "hexBinned": ["#003276", "#005B74", "#00807F", "#64A28F", "#A1C1A8", "#D3DDC8", "#F6F4E7"],
        "warnings": []
      },
      {
        "id": "hfv-seq-leaf-experimental-hfv-secondary-cream-standard",
        "brand": "hfv",
        "type": "sequential",
        "anchorLabel": "Leaf (experimental HFV secondary) -> cream",
        "inspiration": {
          "dark": "Leaf (experimental HFV secondary)",
          "light": "shared cream (H~80, C~10)"
        },
        "nudgeNote": "Off Leaf (experimental HFV secondary): hue +0° (source 118° -> final 118°), chroma 73 -> 65 (dark end), luminance 67 -> 28 (dark end); light end anchors to a shared cream tone (H~80, C~10) at L~95, not this color's own hue.",
        "variant": "standard",
        "variantLabel": "Standard (linear HCL sweep)",
        "params": {
          "h1": 118.4931,
          "c1": 65,
          "l1": 28,
          "l2": 95,
          "power": 1,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -7.8368,
        "hexSmooth": ["#005000", "#0D5400", "#1D5900", "#295E00", "#336200", "#3C6700", "#446C00", "#4D7004", "#55751A", "#5C7A27", "#647F32", "#6C843C", "#738945", "#7A8E4E", "#829357", "#899860", "#909D68", "#97A270", "#9EA879", "#A5AD81", "#ACB289", "#B2B891", "#B9BD9A", "#C0C3A2", "#C6C8AA", "#CDCEB2", "#D4D4BB", "#DAD9C3", "#E0DFCB", "#E7E5D4", "#EDEBDC", "#F3F1E4"],
        "hexBinned": ["#005000", "#3D6800", "#678136", "#8C9B64", "#B0B68F", "#D2D3B9", "#F3F1E4"],
        "warnings": []
      },
      {
        "id": "hfv-seq-leaf-experimental-hfv-secondary-cream-wide_contrast",
        "brand": "hfv",
        "type": "sequential",
        "anchorLabel": "Leaf (experimental HFV secondary) -> cream",
        "inspiration": {
          "dark": "Leaf (experimental HFV secondary)",
          "light": "shared cream (H~80, C~10)"
        },
        "nudgeNote": "Off Leaf (experimental HFV secondary): hue +0° (source 118° -> final 118°), chroma 73 -> 65 (dark end), luminance 67 -> 28 (dark end); light end anchors to a shared cream tone (H~80, C~10) at L~95, not this color's own hue.",
        "variant": "wide_contrast",
        "variantLabel": "Wide-contrast (deeper dark end, punchier chroma, eased curve)",
        "params": {
          "h1": 118.4931,
          "c1": 77,
          "l1": 22,
          "l2": 96,
          "power": 1.2,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -7.8368,
        "hexSmooth": ["#004400", "#004A00", "#005000", "#125600", "#235C00", "#306200", "#3B6800", "#456E00", "#4F7400", "#597A11", "#628026", "#6B8635", "#748C42", "#7D924D", "#869858", "#8E9E63", "#96A46D", "#9EAA77", "#A6B080", "#AEB68A", "#B5BC93", "#BCC19C", "#C3C7A5", "#CACDAE", "#D1D3B6", "#D7D8BE", "#DDDDC6", "#E3E3CE", "#E9E8D5", "#EEECDC", "#F2F1E3", "#F6F4E7"],
        "hexBinned": ["#004400", "#326300", "#65822B", "#92A168", "#BAC099", "#DCDDC5", "#F6F4E7"],
        "warnings": []
      },
      {
        "id": "hfv-seq-berry-cream-standard",
        "brand": "hfv",
        "type": "sequential",
        "anchorLabel": "Berry -> cream",
        "inspiration": {
          "dark": "Berry",
          "light": "shared cream (H~80, C~10)"
        },
        "nudgeNote": "Off Berry: hue +0° (source 344° -> final 344°), chroma 87 -> 80 (dark end), luminance 46 -> 30 (dark end); light end anchors to a shared cream tone (H~80, C~10) at L~95, not this color's own hue.",
        "variant": "standard",
        "variantLabel": "Standard (linear HCL sweep)",
        "params": {
          "h1": 343.9945,
          "c1": 80,
          "l1": 30,
          "l2": 95,
          "power": 1,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -6.5351,
        "hexSmooth": ["#930058", "#970069", "#990079", "#981986", "#962B92", "#923A9C", "#8B48A5", "#8355AC", "#7A61B1", "#706CB5", "#6576B7", "#5A80B9", "#5089B9", "#4791B9", "#4299B8", "#42A0B7", "#46A7B5", "#4EADB3", "#5AB3B2", "#66B9B1", "#74BEB0", "#81C3B0", "#8FC7B1", "#9DCCB3", "#AAD1B5", "#B6D5B9", "#C2D9BE", "#CEDEC5", "#D8E2CC", "#E2E7D3", "#EBECDC", "#F3F1E4"],
        "hexBinned": ["#930058", "#913D9E", "#617AB8", "#43A4B6", "#7DC1B0", "#C0D9BE", "#F3F1E4"],
        "warnings": []
      },
      {
        "id": "hfv-seq-berry-cream-wide_contrast",
        "brand": "hfv",
        "type": "sequential",
        "anchorLabel": "Berry -> cream",
        "inspiration": {
          "dark": "Berry",
          "light": "shared cream (H~80, C~10)"
        },
        "nudgeNote": "Off Berry: hue +0° (source 344° -> final 344°), chroma 87 -> 80 (dark end), luminance 46 -> 30 (dark end); light end anchors to a shared cream tone (H~80, C~10) at L~95, not this color's own hue.",
        "variant": "wide_contrast",
        "variantLabel": "Wide-contrast (deeper dark end, punchier chroma, eased curve)",
        "params": {
          "h1": 343.9945,
          "c1": 92,
          "l1": 24,
          "l2": 96,
          "power": 1.2,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -6.5351,
        "hexSmooth": ["#8E004E", "#940063", "#970075", "#980084", "#960092", "#91269D", "#8B3CA7", "#824DAE", "#795CB4", "#6E6AB8", "#6376BB", "#5881BD", "#4E8BBE", "#4795BE", "#449EBD", "#46A6BD", "#4DADBB", "#58B4BA", "#64BBB9", "#72C1B9", "#80C6B9", "#8ECCBA", "#9CD1BB", "#AAD5BE", "#B6DAC1", "#C2DEC5", "#CEE2CA", "#D8E6D0", "#E1EAD6", "#E9EEDC", "#F0F1E2", "#F6F4E7"],
        "hexBinned": ["#8E004E", "#912A9F", "#5F7ABC", "#49AABC", "#8ACAB9", "#CCE2C9", "#F6F4E7"],
        "warnings": []
      }
    ],
    "diverging": [
      {
        "id": "hfv-div-shadow-vs-desert-standard",
        "brand": "hfv",
        "type": "diverging",
        "anchorLabel": "Shadow vs Desert",
        "inspiration": {
          "arm1": "Shadow",
          "arm2": "Desert"
        },
        "nudgeNote": "Off Shadow (arm 1, hue 247°) and Desert (arm 2, hue 25°): shared chroma target 55 (arm1 source C=27, arm2 source C=96), luminance sweep 28 -> 95 into a shared cream center (H~80, C~10), not a fully neutral one.",
        "variant": "standard",
        "variantLabel": "Standard (linear HCL sweep)",
        "params": {
          "h1": 246.5788,
          "h2": 24.5446,
          "c1": 55,
          "l1": 28,
          "l2": 95,
          "power": 1,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -6.3624,
        "hexSmooth": ["#00467E", "#00557F", "#006280", "#006F82", "#007A83", "#008685", "#349187", "#519C8B", "#6BA690", "#82B197", "#98BB9F", "#ADC5AA", "#C0D0B6", "#D2DAC5", "#E3E5D4", "#F3F1E4", "#F3F1E4", "#E8E4D4", "#DDD7C4", "#D4CAB4", "#CABDA5", "#C1B095", "#B8A386", "#B09678", "#A8896A", "#A07D5C", "#98704E", "#906341", "#885634", "#804928", "#783C1A", "#702E0B"],
        "hexBinned": ["#00467E", "#008685", "#98BB9F", "#F3F1E4", "#C1B095", "#98704E", "#702E0B"],
        "warnings": []
      },
      {
        "id": "hfv-div-shadow-vs-desert-wide_contrast",
        "brand": "hfv",
        "type": "diverging",
        "anchorLabel": "Shadow vs Desert",
        "inspiration": {
          "arm1": "Shadow",
          "arm2": "Desert"
        },
        "nudgeNote": "Off Shadow (arm 1, hue 247°) and Desert (arm 2, hue 25°): shared chroma target 55 (arm1 source C=27, arm2 source C=96), luminance sweep 28 -> 95 into a shared cream center (H~80, C~10), not a fully neutral one.",
        "variant": "wide_contrast",
        "variantLabel": "Wide-contrast (deeper dark end, punchier chroma, eased curve)",
        "params": {
          "h1": 246.5788,
          "h2": 24.5446,
          "c1": 67,
          "l1": 22,
          "l2": 96,
          "power": 1.2,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -6.3624,
        "hexSmooth": ["#003B86", "#004D81", "#005D80", "#006C82", "#007A84", "#008887", "#26958B", "#50A290", "#6EAE96", "#89B99F", "#A1C5A9", "#B7CFB4", "#CBDAC1", "#DCE4CF", "#EBEDDC", "#F6F4E7", "#F6F4E7", "#EFECDC", "#E7E1CF", "#DED4BF", "#D4C7AF", "#CBBA9F", "#C1AC8E", "#B89D7D", "#AE8E6B", "#A57F5A", "#9B6F48", "#915F36", "#874F22", "#7D3F04", "#722D00", "#671900"],
        "hexBinned": ["#003B86", "#008887", "#A1C5A9", "#F6F4E7", "#CBBA9F", "#9B6F48", "#671900"],
        "warnings": []
      },
      {
        "id": "hfv-div-leaf-experimental-hfv-secondary-vs-berry-standard",
        "brand": "hfv",
        "type": "diverging",
        "anchorLabel": "Leaf (experimental HFV secondary) vs Berry",
        "inspiration": {
          "arm1": "Leaf (experimental HFV secondary)",
          "arm2": "Berry"
        },
        "nudgeNote": "Off Leaf (experimental HFV secondary) (arm 1, hue 118°) and Berry (arm 2, hue 344°): shared chroma target 62 (arm1 source C=73, arm2 source C=87), luminance sweep 28 -> 95 into a shared cream center (H~80, C~10), not a fully neutral one.",
        "variant": "standard",
        "variantLabel": "Standard (linear HCL sweep)",
        "params": {
          "h1": 118.4931,
          "h2": 343.9945,
          "c1": 62,
          "l1": 28,
          "l2": 95,
          "power": 1,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -17.686,
        "hexSmooth": ["#005000", "#215900", "#366200", "#476C00", "#587624", "#67803A", "#768B4C", "#85955E", "#94A06F", "#A2AB7F", "#B0B690", "#BEC1A1", "#CCCDB2", "#D9D9C2", "#E6E5D3", "#F3F1E4", "#F3F1E4", "#E1E6D4", "#CDDCC6", "#B7D2BA", "#9FC8B3", "#87BDAF", "#71B2AD", "#60A5AD", "#5797AD", "#5A88AC", "#6577A8", "#7264A1", "#7E4F95", "#853883", "#86226C", "#800C50"],
        "hexBinned": ["#005000", "#67803A", "#B0B690", "#F3F1E4", "#87BDAF", "#6577A8", "#800C50"],
        "warnings": []
      },
      {
        "id": "hfv-div-leaf-experimental-hfv-secondary-vs-berry-wide_contrast",
        "brand": "hfv",
        "type": "diverging",
        "anchorLabel": "Leaf (experimental HFV secondary) vs Berry",
        "inspiration": {
          "arm1": "Leaf (experimental HFV secondary)",
          "arm2": "Berry"
        },
        "nudgeNote": "Off Leaf (experimental HFV secondary) (arm 1, hue 118°) and Berry (arm 2, hue 344°): shared chroma target 62 (arm1 source C=73, arm2 source C=87), luminance sweep 28 -> 95 into a shared cream center (H~80, C~10), not a fully neutral one.",
        "variant": "wide_contrast",
        "variantLabel": "Wide-contrast (deeper dark end, punchier chroma, eased curve)",
        "params": {
          "h1": 118.4931,
          "h2": 343.9945,
          "c1": 74,
          "l1": 22,
          "l2": 96,
          "power": 1.2,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -17.686,
        "hexSmooth": ["#004300", "#005000", "#275C00", "#3E6800", "#537505", "#668130", "#788E49", "#8A9A5F", "#9BA774", "#ABB387", "#BABF9A", "#C8CBAC", "#D6D7BD", "#E2E2CD", "#EDECDC", "#F6F4E7", "#F6F4E7", "#E9EDDC", "#D7E5D0", "#C2DCC6", "#AAD2BE", "#91C7B8", "#79BAB6", "#64ADB5", "#589DB4", "#588BB2", "#6377AD", "#7160A5", "#7D4597", "#852383", "#850069", "#7D0046"],
        "hexBinned": ["#004300", "#668130", "#BABF9A", "#F6F4E7", "#91C7B8", "#6377AD", "#7D0046"],
        "warnings": []
      },
      {
        "id": "hfv-div-cerulean-experimental-hfv-secondary-vs-desert-standard",
        "brand": "hfv",
        "type": "diverging",
        "anchorLabel": "Cerulean (experimental HFV secondary) vs Desert",
        "inspiration": {
          "arm1": "Cerulean (experimental HFV secondary)",
          "arm2": "Desert"
        },
        "nudgeNote": "Off Cerulean (experimental HFV secondary) (arm 1, hue 220°) and Desert (arm 2, hue 25°): shared chroma target 55 (arm1 source C=44, arm2 source C=96), luminance sweep 28 -> 95 into a shared cream center (H~80, C~10), not a fully neutral one.",
        "variant": "standard",
        "variantLabel": "Standard (linear HCL sweep)",
        "params": {
          "h1": 220.1865,
          "h2": 24.5446,
          "c1": 55,
          "l1": 28,
          "l2": 95,
          "power": 1,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -14.7947,
        "hexSmooth": ["#00516F", "#005C6F", "#006770", "#007272", "#007C74", "#0C8777", "#3D917B", "#5A9B81", "#72A688", "#88B091", "#9DBA9C", "#B0C4A8", "#C2CFB5", "#D4DAC4", "#E4E5D4", "#F3F1E4", "#F3F1E4", "#E8E4D4", "#DDD7C4", "#D4CAB4", "#CABDA5", "#C1B095", "#B8A386", "#B09678", "#A8896A", "#A07D5C", "#98704E", "#906341", "#885634", "#804928", "#783C1A", "#702E0B"],
        "hexBinned": ["#00516F", "#0C8777", "#9DBA9C", "#F3F1E4", "#C1B095", "#98704E", "#702E0B"],
        "warnings": []
      },
      {
        "id": "hfv-div-cerulean-experimental-hfv-secondary-vs-desert-wide_contrast",
        "brand": "hfv",
        "type": "diverging",
        "anchorLabel": "Cerulean (experimental HFV secondary) vs Desert",
        "inspiration": {
          "arm1": "Cerulean (experimental HFV secondary)",
          "arm2": "Desert"
        },
        "nudgeNote": "Off Cerulean (experimental HFV secondary) (arm 1, hue 220°) and Desert (arm 2, hue 25°): shared chroma target 55 (arm1 source C=44, arm2 source C=96), luminance sweep 28 -> 95 into a shared cream center (H~80, C~10), not a fully neutral one.",
        "variant": "wide_contrast",
        "variantLabel": "Wide-contrast (deeper dark end, punchier chroma, eased curve)",
        "params": {
          "h1": 220.1865,
          "h2": 24.5446,
          "c1": 67,
          "l1": 22,
          "l2": 96,
          "power": 1.2,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -14.7947,
        "hexSmooth": ["#004A6E", "#00566C", "#00636D", "#006F6F", "#007C73", "#008978", "#33957D", "#59A185", "#76AD8E", "#8FB999", "#A6C4A5", "#BBCFB2", "#CDD9C1", "#DDE3CF", "#EBEDDC", "#F6F4E7", "#F6F4E7", "#EFECDC", "#E7E1CF", "#DED4BF", "#D4C7AF", "#CBBA9F", "#C1AC8E", "#B89D7D", "#AE8E6B", "#A57F5A", "#9B6F48", "#915F36", "#874F22", "#7D3F04", "#722D00", "#671900"],
        "hexBinned": ["#004A6E", "#008978", "#A6C4A5", "#F6F4E7", "#CBBA9F", "#9B6F48", "#671900"],
        "warnings": []
      }
    ]
  },
  "pha": {
    "sequential": [
      {
        "id": "pha-seq-dark-blue-cream-standard",
        "brand": "pha",
        "type": "sequential",
        "anchorLabel": "Dark Blue -> cream",
        "inspiration": {
          "dark": "Dark Blue",
          "light": "shared cream (H~80, C~10)"
        },
        "nudgeNote": "Off Dark Blue: hue +0° (source 243° -> final 243°), chroma 53 -> 58 (dark end), luminance 43 -> 26 (dark end); light end anchors to a shared cream tone (H~80, C~10) at L~95, not this color's own hue.",
        "variant": "standard",
        "variantLabel": "Standard (linear HCL sweep)",
        "params": {
          "h1": 243.4067,
          "c1": 58,
          "l1": 26,
          "l2": 95,
          "power": 1,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": 5.4635,
        "hexSmooth": ["#00447D", "#004B7D", "#00527C", "#00587D", "#005F7D", "#00657D", "#006B7E", "#00717E", "#00767F", "#007C7F", "#008280", "#008781", "#1D8C83", "#339284", "#439786", "#529C88", "#5FA18A", "#6CA78D", "#78AC91", "#83B195", "#8EB699", "#99BB9E", "#A3C0A3", "#AEC5A9", "#B7CAAF", "#C1D0B6", "#CAD5BD", "#D3DAC4", "#DBE0CC", "#E4E5D4", "#EBEBDC", "#F3F1E4"],
        "hexBinned": ["#00447D", "#00667D", "#008381", "#599F89", "#95B99C", "#C9D4BC", "#F3F1E4"],
        "warnings": []
      },
      {
        "id": "pha-seq-dark-blue-cream-wide_contrast",
        "brand": "pha",
        "type": "sequential",
        "anchorLabel": "Dark Blue -> cream",
        "inspiration": {
          "dark": "Dark Blue",
          "light": "shared cream (H~80, C~10)"
        },
        "nudgeNote": "Off Dark Blue: hue +0° (source 243° -> final 243°), chroma 53 -> 58 (dark end), luminance 43 -> 26 (dark end); light end anchors to a shared cream tone (H~80, C~10) at L~95, not this color's own hue.",
        "variant": "wide_contrast",
        "variantLabel": "Wide-contrast (deeper dark end, punchier chroma, eased curve)",
        "params": {
          "h1": 243.4067,
          "c1": 70,
          "l1": 20,
          "l2": 96,
          "power": 1.2,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": 5.4635,
        "hexSmooth": ["#003B88", "#004381", "#004B7E", "#00537D", "#005A7D", "#00617D", "#00687E", "#006F7E", "#007680", "#007D81", "#008482", "#008A84", "#009186", "#299788", "#419D8A", "#53A38D", "#63A991", "#71AF94", "#7FB599", "#8CBA9D", "#98C0A2", "#A3C5A8", "#AECAAE", "#B9D0B4", "#C2D5BB", "#CCDAC1", "#D5DFC8", "#DDE4CF", "#E4E8D6", "#EBEDDD", "#F1F1E3", "#F6F4E7"],
        "hexBinned": ["#003B88", "#00627D", "#008683", "#5BA68F", "#9FC3A6", "#D3DEC7", "#F6F4E7"],
        "warnings": []
      },
      {
        "id": "pha-seq-red-cream-standard",
        "brand": "pha",
        "type": "sequential",
        "anchorLabel": "Red -> cream",
        "inspiration": {
          "dark": "Red",
          "light": "shared cream (H~80, C~10)"
        },
        "nudgeNote": "Off Red: hue +0° (source 20° -> final 20°), chroma 104 -> 90 (dark end), luminance 46 -> 28 (dark end); light end anchors to a shared cream tone (H~80, C~10) at L~95, not this color's own hue.",
        "variant": "standard",
        "variantLabel": "Standard (linear HCL sweep)",
        "params": {
          "h1": 19.6527,
          "c1": 90,
          "l1": 28,
          "l2": 95,
          "power": 1,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -13.5526,
        "hexSmooth": ["#841800", "#882300", "#8B2C00", "#8F3500", "#923D00", "#964400", "#994B00", "#9C5308", "#A05A17", "#A36122", "#A6682B", "#A96E34", "#AC753D", "#B07C45", "#B3834E", "#B68956", "#B9905F", "#BC9767", "#BF9D70", "#C3A478", "#C6AB81", "#C9B18A", "#CDB892", "#D0BE9B", "#D4C5A4", "#D8CBAD", "#DCD2B6", "#E0D8BF", "#E4DEC9", "#E9E5D2", "#EEEBDB", "#F3F1E4"],
        "hexBinned": ["#841800", "#964500", "#A76A2E", "#B78D5B", "#C8AF87", "#DBD0B5", "#F3F1E4"],
        "warnings": []
      },
      {
        "id": "pha-seq-red-cream-wide_contrast",
        "brand": "pha",
        "type": "sequential",
        "anchorLabel": "Red -> cream",
        "inspiration": {
          "dark": "Red",
          "light": "shared cream (H~80, C~10)"
        },
        "nudgeNote": "Off Red: hue +0° (source 20° -> final 20°), chroma 104 -> 90 (dark end), luminance 46 -> 28 (dark end); light end anchors to a shared cream tone (H~80, C~10) at L~95, not this color's own hue.",
        "variant": "wide_contrast",
        "variantLabel": "Wide-contrast (deeper dark end, punchier chroma, eased curve)",
        "params": {
          "h1": 19.6527,
          "c1": 100,
          "l1": 22,
          "l2": 96,
          "power": 1.2,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -13.5526,
        "hexSmooth": ["#780000", "#7D0900", "#821B00", "#872700", "#8C3200", "#913B00", "#964500", "#9A4E00", "#9F5600", "#A35F17", "#A76727", "#AB6F33", "#B0773E", "#B47F49", "#B78753", "#BB8F5D", "#BF9767", "#C39E71", "#C7A67B", "#CAAD84", "#CEB48E", "#D2BB97", "#D5C2A0", "#D9C9A9", "#DDCFB2", "#E1D5BB", "#E5DBC4", "#E8E1CC", "#ECE7D4", "#F0ECDB", "#F3F0E2", "#F6F4E7"],
        "hexBinned": ["#780000", "#923D00", "#A96A2B", "#BD9362", "#D1B994", "#E4DAC2", "#F6F4E7"],
        "warnings": []
      },
      {
        "id": "pha-seq-green-cream-standard",
        "brand": "pha",
        "type": "sequential",
        "anchorLabel": "Green -> cream",
        "inspiration": {
          "dark": "Green",
          "light": "shared cream (H~80, C~10)"
        },
        "nudgeNote": "Off Green: hue +0° (source 157° -> final 157°), chroma 40 -> 52 (dark end), luminance 64 -> 26 (dark end); light end anchors to a shared cream tone (H~80, C~10) at L~95, not this color's own hue.",
        "variant": "standard",
        "variantLabel": "Standard (linear HCL sweep)",
        "params": {
          "h1": 156.875,
          "c1": 52,
          "l1": 26,
          "l2": 95,
          "power": 1,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": 12.4345,
        "hexSmooth": ["#004F27", "#00542A", "#00582E", "#005D31", "#006235", "#006639", "#016B3D", "#1F7042", "#307546", "#3D7A4B", "#487E51", "#538356", "#5D885C", "#668D62", "#6F9268", "#78986E", "#819D74", "#8AA27B", "#92A782", "#9AAC89", "#A2B290", "#AAB797", "#B2BD9E", "#BAC2A6", "#C1C8AD", "#C9CEB5", "#D0D3BD", "#D7D9C5", "#DEDFCC", "#E5E5D4", "#ECEBDC", "#F3F1E4"],
        "hexBinned": ["#004F27", "#006739", "#4C8052", "#7D9A71", "#A7B595", "#CFD2BB", "#F3F1E4"],
        "warnings": []
      },
      {
        "id": "pha-seq-green-cream-wide_contrast",
        "brand": "pha",
        "type": "sequential",
        "anchorLabel": "Green -> cream",
        "inspiration": {
          "dark": "Green",
          "light": "shared cream (H~80, C~10)"
        },
        "nudgeNote": "Off Green: hue +0° (source 157° -> final 157°), chroma 40 -> 52 (dark end), luminance 64 -> 26 (dark end); light end anchors to a shared cream tone (H~80, C~10) at L~95, not this color's own hue.",
        "variant": "wide_contrast",
        "variantLabel": "Wide-contrast (deeper dark end, punchier chroma, eased curve)",
        "params": {
          "h1": 156.875,
          "c1": 64,
          "l1": 20,
          "l2": 96,
          "power": 1.2,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": 12.4345,
        "hexSmooth": ["#00450F", "#004B14", "#005119", "#00561E", "#005C24", "#00622A", "#006830", "#006E37", "#1B743D", "#317A44", "#41804B", "#4F8652", "#5B8C5A", "#679261", "#729869", "#7C9E71", "#86A479", "#90AA81", "#9AB089", "#A3B691", "#ABBC99", "#B4C1A1", "#BCC7A9", "#C4CDB1", "#CCD3B9", "#D3D8C0", "#DADDC8", "#E1E3CF", "#E7E8D6", "#EDECDD", "#F2F1E3", "#F6F4E7"],
        "hexBinned": ["#00450F", "#00632B", "#46824E", "#81A175", "#B1C09E", "#D9DCC7", "#F6F4E7"],
        "warnings": []
      }
    ],
    "diverging": [
      {
        "id": "pha-div-dark-blue-vs-red-standard",
        "brand": "pha",
        "type": "diverging",
        "anchorLabel": "Dark Blue vs Red",
        "inspiration": {
          "arm1": "Dark Blue",
          "arm2": "Red"
        },
        "nudgeNote": "Off Dark Blue (arm 1, hue 243°) and Red (arm 2, hue 20°): shared chroma target 65 (arm1 source C=53, arm2 source C=104), luminance sweep 28 -> 95 into a shared cream center (H~80, C~10), not a fully neutral one.",
        "variant": "standard",
        "variantLabel": "Standard (linear HCL sweep)",
        "params": {
          "h1": 243.4067,
          "h2": 19.6527,
          "c1": 65,
          "l1": 28,
          "l2": 95,
          "power": 1,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -13.0446,
        "hexSmooth": ["#004988", "#005886", "#006585", "#007185", "#007D85", "#008885", "#0C9387", "#439E89", "#62A88D", "#7DB293", "#95BC9C", "#ABC6A7", "#BFD0B4", "#D2DBC3", "#E3E6D3", "#F3F1E4", "#F3F1E4", "#E8E4D3", "#DED7C2", "#D5CAB2", "#CCBDA1", "#C4B092", "#BCA282", "#B49573", "#AC8864", "#A57B56", "#9D6D49", "#96603C", "#8F532F", "#874523", "#7F3716", "#782709"],
        "hexBinned": ["#004988", "#008885", "#95BC9C", "#F3F1E4", "#C4B092", "#9D6D49", "#782709"],
        "warnings": []
      },
      {
        "id": "pha-div-dark-blue-vs-red-wide_contrast",
        "brand": "pha",
        "type": "diverging",
        "anchorLabel": "Dark Blue vs Red",
        "inspiration": {
          "arm1": "Dark Blue",
          "arm2": "Red"
        },
        "nudgeNote": "Off Dark Blue (arm 1, hue 243°) and Red (arm 2, hue 20°): shared chroma target 65 (arm1 source C=53, arm2 source C=104), luminance sweep 28 -> 95 into a shared cream center (H~80, C~10), not a fully neutral one.",
        "variant": "wide_contrast",
        "variantLabel": "Wide-contrast (deeper dark end, punchier chroma, eased curve)",
        "params": {
          "h1": 243.4067,
          "h2": 19.6527,
          "c1": 77,
          "l1": 22,
          "l2": 96,
          "power": 1.2,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -13.0446,
        "hexSmooth": ["#004092", "#005188", "#006085", "#006F85", "#007D85", "#008A87", "#00978A", "#42A38E", "#67AF94", "#85BB9C", "#9FC5A6", "#B6D0B2", "#CADAC0", "#DCE4CE", "#EBEDDC", "#F6F4E7", "#F6F4E7", "#EFEBDC", "#E7E1CD", "#DFD4BE", "#D6C7AD", "#CDB99C", "#C4AB8A", "#BC9C79", "#B38D67", "#AA7D55", "#A16D43", "#975C30", "#8D4C1B", "#833A00", "#792600", "#6E0C00"],
        "hexBinned": ["#004092", "#008A87", "#9FC5A6", "#F6F4E7", "#CDB99C", "#A16D43", "#6E0C00"],
        "warnings": []
      },
      {
        "id": "pha-div-dark-blue-vs-orange-standard",
        "brand": "pha",
        "type": "diverging",
        "anchorLabel": "Dark Blue vs Orange",
        "inspiration": {
          "arm1": "Dark Blue",
          "arm2": "Orange"
        },
        "nudgeNote": "Off Dark Blue (arm 1, hue 243°) and Orange (arm 2, hue 33°): shared chroma target 60 (arm1 source C=53, arm2 source C=91), luminance sweep 28 -> 95 into a shared cream center (H~80, C~10), not a fully neutral one.",
        "variant": "standard",
        "variantLabel": "Standard (linear HCL sweep)",
        "params": {
          "h1": 243.4067,
          "h2": 32.7145,
          "c1": 60,
          "l1": 28,
          "l2": 95,
          "power": 1,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -12.0097,
        "hexSmooth": ["#004883", "#005782", "#006482", "#007083", "#007C83", "#008784", "#269286", "#4B9D89", "#67A78E", "#80B195", "#96BB9D", "#ACC5A8", "#C0D0B5", "#D2DAC4", "#E3E6D4", "#F3F1E4", "#F3F1E4", "#E8E4D4", "#DDD7C3", "#D3CAB3", "#CABDA3", "#C1B193", "#B8A483", "#AF9773", "#A78A64", "#9F7D55", "#977145", "#8F6436", "#875725", "#7F4B0F", "#773E00", "#6F3100"],
        "hexBinned": ["#004883", "#008784", "#96BB9D", "#F3F1E4", "#C1B193", "#977145", "#6F3100"],
        "warnings": []
      },
      {
        "id": "pha-div-dark-blue-vs-orange-wide_contrast",
        "brand": "pha",
        "type": "diverging",
        "anchorLabel": "Dark Blue vs Orange",
        "inspiration": {
          "arm1": "Dark Blue",
          "arm2": "Orange"
        },
        "nudgeNote": "Off Dark Blue (arm 1, hue 243°) and Orange (arm 2, hue 33°): shared chroma target 60 (arm1 source C=53, arm2 source C=91), luminance sweep 28 -> 95 into a shared cream center (H~80, C~10), not a fully neutral one.",
        "variant": "wide_contrast",
        "variantLabel": "Wide-contrast (deeper dark end, punchier chroma, eased curve)",
        "params": {
          "h1": 243.4067,
          "h2": 32.7145,
          "c1": 72,
          "l1": 22,
          "l2": 96,
          "power": 1.2,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": -12.0097,
        "hexSmooth": ["#003F8B", "#005083", "#005F82", "#006E82", "#007C84", "#008986", "#119689", "#4AA38E", "#6BAF94", "#87BA9D", "#A0C5A7", "#B7D0B3", "#CBDAC1", "#DCE4CF", "#EBEDDC", "#F6F4E7", "#F6F4E7", "#EFECDC", "#E6E1CE", "#DDD5BE", "#D4C8AE", "#CABA9C", "#C1AC8B", "#B79E78", "#AD8F66", "#A48053", "#9A703E", "#906127", "#855100", "#7B4100", "#703000", "#651E00"],
        "hexBinned": ["#003F8B", "#008986", "#A0C5A7", "#F6F4E7", "#CABA9C", "#9A703E", "#651E00"],
        "warnings": []
      },
      {
        "id": "pha-div-purple-vs-green-standard",
        "brand": "pha",
        "type": "diverging",
        "anchorLabel": "Purple vs Green",
        "inspiration": {
          "arm1": "Purple",
          "arm2": "Green"
        },
        "nudgeNote": "Off Purple (arm 1, hue 258°) and Green (arm 2, hue 157°): shared chroma target 45 (arm1 source C=30, arm2 source C=40), luminance sweep 28 -> 95 into a shared cream center (H~80, C~10), not a fully neutral one.",
        "variant": "standard",
        "variantLabel": "Standard (linear HCL sweep)",
        "params": {
          "h1": 258.2729,
          "h2": 156.875,
          "c1": 45,
          "l1": 28,
          "l2": 95,
          "power": 1,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": 10.0981,
        "hexSmooth": ["#2C4076", "#1F4F7A", "#145D7E", "#146A81", "#227784", "#348388", "#488E8B", "#5D9A8F", "#71A594", "#86AF9B", "#9ABAA3", "#ADC5AD", "#C0CFB9", "#D2DAC6", "#E3E5D5", "#F3F1E4", "#F3F1E4", "#E5E5D5", "#D7D9C5", "#C8CDB6", "#B9C2A8", "#AAB799", "#9AAC8B", "#8AA17E", "#799772", "#688C66", "#55825B", "#417850", "#276E47", "#00653E", "#005B36", "#005230"],
        "hexBinned": ["#2C4076", "#348388", "#9ABAA3", "#F3F1E4", "#AAB799", "#55825B", "#005230"],
        "warnings": []
      },
      {
        "id": "pha-div-purple-vs-green-wide_contrast",
        "brand": "pha",
        "type": "diverging",
        "anchorLabel": "Purple vs Green",
        "inspiration": {
          "arm1": "Purple",
          "arm2": "Green"
        },
        "nudgeNote": "Off Purple (arm 1, hue 258°) and Green (arm 2, hue 157°): shared chroma target 45 (arm1 source C=30, arm2 source C=40), luminance sweep 28 -> 95 into a shared cream center (H~80, C~10), not a fully neutral one.",
        "variant": "wide_contrast",
        "variantLabel": "Wide-contrast (deeper dark end, punchier chroma, eased curve)",
        "params": {
          "h1": 258.2729,
          "h2": 156.875,
          "c1": 57,
          "l1": 22,
          "l2": 96,
          "power": 1.2,
          "hc": 80,
          "cc": 10
        },
        "sourceHueDelta": 0,
        "sourceChromaDelta": 10.0981,
        "hexSmooth": ["#00307C", "#00467C", "#00577F", "#006783", "#007787", "#17858B", "#3D938F", "#5AA094", "#74AD9B", "#8CB9A3", "#A2C4AC", "#B7CFB7", "#CBDAC4", "#DCE4D0", "#EBEDDD", "#F6F4E7", "#F6F4E7", "#EDECDD", "#E0E2CF", "#D3D8C1", "#C4CCB1", "#B3C1A2", "#A2B592", "#8FA982", "#7C9D73", "#669064", "#4F8455", "#327848", "#006C3B", "#005F2F", "#005424", "#00481A"],
        "hexBinned": ["#00307C", "#17858B", "#A2C4AC", "#F6F4E7", "#B3C1A2", "#4F8455", "#00481A"],
        "warnings": []
      }
    ]
  }
};
